# Generated by Django 2.1.1 on 2018-09-26 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_dat',
            new_name='pub_date',
        ),
    ]
